sudo: required
services:
  - docker


script:
  - docker build -t sravyachinthu/react-example .
  - docker images sravyachinthu/react-example

deploy:
  provider: script
  script: docker push sravyachinthu/react-example
  on:
    branch: master
