sudo: required
services:
  - docker


script:
  - docker build -t sravyachinthu/react-example2 .
  - docker images sravyachinthu/react-example2

deploy:
  provider: script
  script: docker push sravyachinthu/react-example2
  on:
    branch: master
